In [3]:
import numpy as np

In [3]:
def randomization(n):
    A = np.random.random([n,1])
    return(A)
randomization(5)


array([[0.53604546],
       [0.01169917],
       [0.82355887],
       [0.6097695 ],
       [0.39704521]])

In [7]:
def operations(h, w):
    A = np.random.random([h, w])
    B = np.random.random([h, w])

    s = A + B

    return (A, B, s) 
operations(3, 5)


(array([[0.60000868, 0.06616777, 0.89771189, 0.10290579, 0.90856044],
        [0.47292355, 0.12827581, 0.39650492, 0.77689264, 0.28672927],
        [0.61836739, 0.48059726, 0.30204543, 0.87323934, 0.9747773 ]]),
 array([[0.74516487, 0.86628559, 0.90381739, 0.88471326, 0.67219473],
        [0.25762833, 0.49802359, 0.08295977, 0.3405039 , 0.09756802],
        [0.65232752, 0.07364231, 0.22366838, 0.29999709, 0.32976381]]),
 array([[1.34517355, 0.93245336, 1.80152928, 0.98761905, 1.58075517],
        [0.73055188, 0.6262994 , 0.47946469, 1.11739654, 0.38429729],
        [1.27069491, 0.55423957, 0.52571382, 1.17323643, 1.30454112]]))

In [8]:
def norm(A, B):
    s = np.linalg.norm(A+B)
    return s
norm([[1, 2, 3], [4, 5, 6]], [[7,8,9], [10, 11, 12]])

25.495097567963924

In [24]:
import numpy as np
def neural_network(inputs, weights):

  weightsT = np.transpose(weights)
  _out = np.matmul(weightsT, inputs)

  out = np.tanh(_out)
  return out

inputs = [[0.28482398], [0.72773168]]
weights = [[0.34834978], [0.83918207]]
neural_network(inputs, weights)

[[0.61062525]]


array([[0.61062525]])

In [27]:
def scalar_function(x, y):
    if x <= y: return x * y
    elif x > y: return x/y

scalar_function(5,9)


45

In [29]:
def vector_function(x, y):
    def scalar_function(x, y):
        if x <= y: return x * y
        elif x > y: return x/y
    
    funct = np.vectorize(scalar_function)
    
    return funct(x, y)